"""Renderer from ``MergedModel`` to AMPL text."""

from __future__ import annotations

import re

from ..llm.base import prompt_hash
from ..modeling import MergedModel
from .types import AmplRenderResult
from .validator import validate_ampl_model

_FENCE_RE = re.compile(r"^```(?:ampl)?\s*|\s*```$", re.IGNORECASE)
_SECTION_HEADER_RE = re.compile(r"^\s*###\s+[A-Z_ ]+\s*$", re.MULTILINE)


def _clean_block(text: str) -> str:
    cleaned = _FENCE_RE.sub("", text.strip())
    cleaned = _SECTION_HEADER_RE.sub("", cleaned)
    return cleaned.strip()


def render_merged_model(model: MergedModel) -> AmplRenderResult:
    """Render a complete AMPL model from PaMOP's merged representation.

    PAPER-SPECIFIED: PaMOP's model target is AMPL. REPRODUCTION CHOICE:
    because the paper does not publish a renderer interface, this function
    preserves the four generated sections verbatim except for removing
    markdown fences/section headers and adding stable comments.
    """
    parts = [
        "# Generated by the independent PaMOP reproduction scaffold.",
        "# Source sections: parameters, variables, objective, constraints.",
        _clean_block(model.parameters_text),
        _clean_block(model.variables_text),
        _clean_block(model.objective_text),
        _clean_block(model.constraints_text),
    ]
    text = "\n\n".join(part for part in parts if part).strip() + "\n"
    return AmplRenderResult(
        model_text=text,
        model_hash=prompt_hash(text),
        diagnostics=validate_ampl_model(text),
    )
